spring.application.name=perfumaria

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.mjqyczjwhfvogdcmwshx
spring.datasource.password=S1e2n3a4i8i

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true